Bridgeconn/isl-manzil-web

src/components/CustomVideoPlayer.tsx
- #9 
- Added full-screen functionality through button icon as well as keyboard control.
- Removed deprecated youtube player vars of it iframe api
- reduced seek-bar height as per suggestion
=> implemented full-screen functionality

src/components/BibleVerseDisplay.tsx, src/components/Middlebar.tsx, src/components/SelectBoxContainer.tsx, src/index.css, src/pages/HomePage.tsx, src/store/useBibleStore.ts, src/types/Navigation.ts, src/types/bible.ts
Added changes as per QA suggestion as well as review feedback. 
- Implemented zustand store to make bible book, chapter and verse as global state. 
- #11
=> Change font-family of verse text, added bible reference and implemented zustand store

src/components/SelectViewContainer.tsx, src/pages/HomePage.tsx, src/types/bible.ts
=> List-view dropdown

src/components/CustomVideoPlayer.tsx
As per QA suggestion to the issue #24 
- Made the prev gif icon as hidden in case Genesis chapter 1
- Made the next gif icon as hidden in case Rev chapter 22
=> hide prev and next gif in case of gen 1 and rev 22

src/components/CustomVideoPlayer.tsx
- #23 
- Fixed verse seekbar jumping while changing verse during video playing initially
- Fixed seekbar controls showing even after playing or video resume done through screen click
=> Previous and next verse navigation along with minor fixes

src/components/BibleVerseDisplay.tsx, src/components/Settings.tsx, src/index.css, src/store/useThemeStore.ts
=> Settings font#16

src/components/CustomVideoPlayer.tsx, src/components/Layout/Layout.tsx, src/components/Layout/MobileBottomBar.tsx, src/components/SelectBoxContainer.tsx, src/components/SelectViewContainer.tsx, src/hooks/useDeviceDetection.ts, src/hooks/useLayoutControl.ts, src/pages/HomePage.tsx
=> implemented mobile responsive layout for portrait and landscape mode

src/components/Layout/MobileBottomBar.tsx, src/components/MobileMenuDrawer.tsx
=> Mobile settings menu

package.json, pnpm-lock.yaml, src/components/CustomVideoPlayer.tsx, src/components/QualityDrawer.tsx, src/components/SharePopUp.tsx
=> implemented the sharepopup #35

src/components/SharePopUp.tsx, vercel.json
Fix 404 errors on Vercel by adding rewrite rules for SPA routing
=> Sharepopup#35

src/components/CustomVideoPlayer.tsx, src/components/SettingsButton.tsx, src/components/SharePopUp.tsx
=> disable the link and added the QA suggestions#35

src/components/SearchboxBCV.tsx
- #32
https://github.com/Bridgeconn/isl-manzil-web/issues/32#issuecomment-2987505491
=> QA review changes regarding searchbox bug issues and enhancement

src/components/ButtonHide.tsx
=> remove the hide/show Text#95

src/components/BibleVerseDisplay.tsx, src/components/CustomVideoPlayer.tsx, src/components/Layout/MobileBottomBar.tsx
- #88 
- https://github.com/Bridgeconn/isl-manzil-web/issues/59#issuecomment-2989743823
=> Seek forward or backward based on double tap on screeen

package.json, pnpm-lock.yaml, src/hooks/useResizable.ts, src/pages/HomePage.tsx
- #100 
Facing some issues in mobile landscape mode for holding and dragging the resize handle for resizing height, which affecting the whole page to scroll.
=> Resizable verse textbox

src/components/CustomVideoPlayer.tsx
- https://github.com/Bridgeconn/isl-manzil-web/issues/88#issuecomment-2998839209
- #118 
- Additional bug fix - fixed not updating the verse dropdown value as well as not highlighting current verse while video starts playing till any user interaction is done.
=> bug fixes in video player regarding interactivity

src/components/CustomVideoPlayer.tsx
=> Touch dragseek implementation

src/App.css, src/components/BCVDrawer.tsx, src/components/BibleVerseDisplay.tsx, src/components/ButtonHide.tsx, src/components/CustomVideoPlayer.tsx, src/components/Layout/Header.tsx, src/components/Layout/Layout.tsx, src/components/LayoutControlButtons.tsx, src/components/Navbar.tsx, src/components/SearchboxBCV.tsx, src/components/SelectViewContainer.tsx, src/components/Settings.tsx, src/hooks/useDeviceDetection.ts, src/hooks/useLayoutControl.ts, src/hooks/useResizable.ts, src/pages/HomePage.tsx, src/store/useLayoutStore.ts, src/store/useThemeStore.ts
=> implemented top bar changes and desktop layout changes

src/components/BCVDrawer.tsx, src/components/ButtonHide.tsx, src/pages/HomePage.tsx
=> qa suggested changes 

src/components/BCVDrawer.tsx, src/index.css
- #134 
- make book, chapter and verse boxes border edge rounded
- change the disabled buttons bg colour to more user friendly and easy to read 
- change the bcv tabs design
- Implement better and prominent shade for selected item
=> implemented ui changes in bcv pop up

src/store/useBibleStore.ts
- #97 
- https://github.com/Bridgeconn/isl-manzil-web/issues/97#issuecomment-3031926195
=> bug fix related to next chapter

src/App.css, src/pages/HomePage.tsx
=> fixed extra scrollbar issue in text container

src/App.css, src/assets/data/books/exo/exo_intro.md, src/assets/data/books/gen/gen_intro.md, src/assets/data/books/tit/tit_intro.md
- #136 
- https://github.com/Bridgeconn/isl-manzil-web/issues/136#issuecomment-3043965707
=> reduced the gaps or removed margins in some text of book intro

src/components/SearchboxBCV.tsx, src/components/SearchboxToolTip.tsx
=> added searchtooltip#147

src/components/BibleVerseDisplay.tsx
=> added theme text class for "no content available" message

src/components/MobileBookDrawer.tsx
- #131 
https://github.com/Bridgeconn/isl-manzil-web/issues/131#issuecomment-3056440129
=> QA suggestion of showing books under respective testaments in mobile

src/components/BCVDrawer.tsx, src/components/MobileBookDrawer.tsx, src/components/SearchboxBCV.tsx, src/store/useBibleStore.ts
- #149 
https://github.com/Bridgeconn/isl-manzil-web/issues/149#issuecomment-3057076427
=> bible reference search issue 

src/components/SearchboxToolTip.tsx
=> added the QA suggestions

src/components/BCVDrawer.tsx, src/components/MobileBookDrawer.tsx
=> Implement BCV UI changes

src/App.tsx, src/components/BCVDrawer.tsx, src/components/BibleVerseDisplay.tsx, src/components/CustomVideoPlayer.tsx, src/components/Layout/MobileBottomBar.tsx, src/components/MobileBookDrawer.tsx, src/store/useBibleStore.ts
https://github.com/Bridgeconn/isl-manzil-web/issues/105#issuecomment-3068482337
https://github.com/Bridgeconn/isl-manzil-web/issues/176#issuecomment-3068201290
=> Share Url Bug fixes

src/components/AboutUsPopUp.tsx, src/components/CustomVideoPlayer.tsx, src/components/Settings.tsx
=> About us#145

src/components/BCVDrawer.tsx, src/components/CustomVideoPlayer.tsx, src/components/MobileBookDrawer.tsx
=> fix bug issue of delay in highlighting the verse on bcv selection

src/App.css, src/components/BCVDrawer.tsx, src/components/CustomVideoPlayer.tsx, src/components/Layout/MobileBottomBar.tsx, src/components/MobileBookDrawer.tsx, src/components/PlayBackDrawer.tsx, src/components/QualityDrawer.tsx, src/components/Settings.tsx, src/components/SettingsDrawer.tsx, src/components/SharePopUp.tsx, src/store/useThemeStore.ts
- #79 
1. **Dark blue background theme:**
2. 
3.
=> Implement theme changes on pop ups and bcv

src/components/CustomVideoPlayer.tsx, src/store/useBibleStore.ts
=> Quality#21

src/components/BCVDrawer.tsx
=> added dropdown icon to bcv text of drawer

src/App.css, src/components/BCVDrawer.tsx, src/components/Layout/MobileBottomBar.tsx, src/components/SettingsDrawer.tsx, src/pages/HomePage.tsx
=> Bcv popup changes

src/components/BCVDrawer.tsx, src/components/Layout/Header.tsx, src/components/MobileBookDrawer.tsx, src/components/SearchboxBCV.tsx, src/utils/bibleReferenceUtils.ts
=> Implement UI changes

src/components/BCVDrawer.tsx, src/components/MobileBookDrawer.tsx
=> added bcv tab changes in mobile same as desktop and changed error msg
